### ISSUE TITLE
Regarding Stock market price prediction

### ISSUE THREAD

**Issue by gowsik710** [Fluid-AI/marketprophecy#28]
I have completed the prediction process for the bitcoin-stock market price and I don't know where to upload it .so please kindly assist me with this issue as soon as possible

**Comment by fluidai** [comment]
Hi, you can upload it as a part of the pull request itself as an additional file, for more instructions on how to create a pull request pls go to the readme section of this project here

**Comment by gowsik710** [comment]
I have completed my assessment test 1 and test 2 but I couldn't send the
stock price prediction ( assessment test 2 ) on time as I don't know how to
attach the file using pull request. Please let me know whether I got
selected or not for the next round based on assessment test 1.

With regards,
Gowsik Arivazhagan
